#!/bin/sh /etc/rc.common
# for openwrt 25
USE_PROCD=1
START=99
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c '
        cd /etc/autonet || exit 1
        while true; do
            /usr/bin/autonet
            sleep 60
        done
    '
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
