#!/bin/sh /etc/rc.common
# for openwrt 24
# 启动顺序，99 表示最后启动
START=99
# 必须声明使用 PROCD
USE_PROCD=1

PROG=/root/net/net3
DIR=/root/net

start_service() {
    # 检查文件是否存在
    [ -x "$PROG" ] || return 1

    procd_open_instance
    # 切换到程序所在目录，否则它找不到 config.txt
    procd_set_param chdir "$DIR"
    # 启动程序并传参
    procd_set_param command "$PROG" wan

    # 【核心功能】自动守护：如果程序意外退出，5秒后自动拉起
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    # 这里的 stdout/stderr 设为 1 可以把 C++ 的 cout 打印直接喂给 logread
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

# 备注：使用了 USE_PROCD 之后，不需要手动写 stop()，
# 运行 /etc/init.d/autonet stop 时，系统会自动寻找并杀掉该进程。
